# Tweaks to modus vivendi tinted to add some additional syntax highlighting to enhance code and markdown readability
# https://docs.helix-editor.com/themes.html#syntax-highlighting

inherits = "modus_vivendi_tinted"

# Inlay Hints
"ui.virtual.inlay-hint" = { fg = "fg-dim", bg = "bg-dim" }
"ui.virtual.inlay-hint.parameter" = { fg = "fg-dim", bg = "bg-dim" }
"ui.virtual.inlay-hint.type" = { fg = "fg-dim", bg = "bg-dim" }


"" = "fg-dim"
"variable" = "cyan-intense"
"variable.other.member" = "magenta-faint"
"function" = "blue-cooler"
"function.method" = "yellow-intense"
"namespace" = "fg-main"
"attribute" = "fg-clay"
"type" = "fg-alt"
"constant" = "magenta-cooler"
"string" = "fg-dim"
"builtin" = "blue-faint"
"punctuation" = "cyan"
"operator" = "magenta"
"identifier" = "blue-warmer"

"keyword" = "magenta-warmer"


"markup.heading.1" = { fg = "yellow-intense", modifiers = ["bold"] }
"markup.heading.2" = { fg = "yellow-warmer", modifiers = ["bold"] }
"markup.heading.3" = { fg = "yellow-warmer", modifiers = ["bold"] }

"markup.list" = "red-cooler"
"markup.bold" = { modifiers = ["bold"], fg = "cyan-intense" }
"markup.italic" = { modifiers = ["italic"], fg = "fg-lavender" }
"markup.raw" = "fg-clay"

[palette]
# Basic values

bg-main = "#0d0e1c"
bg-dim = "#1d2235"
fg-main = "#ffffff"
fg-dim = "#989898"
fg-alt = "#c6daff"
bg-active = "#4a4f69"
bg-inactive = "#2b3045"
border = "#61647a"

# Common accent foregrounds

red = "#ff5f59"
red-warmer = "#ff6b55"
red-cooler = "#ff7f86"
red-faint = "#ef8386"
red-intense = "#ff5f5f"
green = "#44bc44"
green-warmer = "#75c13e"
green-cooler = "#11c777"
green-faint = "#88ca9f"
green-intense = "#44df44"
yellow = "#d0bc00"
yellow-warmer = "#fec43f"
yellow-cooler = "#dfaf7a"
yellow-faint = "#d2b580"
yellow-intense = "#efef00"
blue = "#2fafff"
blue-warmer = "#79a8ff"
blue-cooler = "#00bcff"
blue-faint = "#82b0ec"
blue-intense = "#338fff"
magenta = "#feacd0"
magenta-warmer = "#f78fe7"
magenta-cooler = "#b6a0ff"
magenta-faint = "#caa6df"
magenta-intense = "#ff66ff"
cyan = "#00d3d0"
cyan-warmer = "#4ae2f0"
cyan-cooler = "#6ae4b9"
cyan-faint = "#9ac8e0"
cyan-intense = "#00eff0"


# Common accent backgrounds

bg-red-intense = "#9d1f1f"
bg-green-intense = "#2f822f"
bg-yellow-intense = "#7a6100"
bg-blue-intense = "#1640b0"
bg-magenta-intense = "#7030af"
bg-cyan-intense = "#2266ae"

bg-red-subtle = "#620f2a"
bg-green-subtle = "#00422a"
bg-yellow-subtle = "#4a4000"
bg-blue-subtle = "#242679"
bg-magenta-subtle = "#552f5f"
bg-cyan-subtle = "#004065"

bg-red-nuanced = "#3a0c14"
bg-green-nuanced = "#092f1f"
bg-yellow-nuanced = "#381d0f"
bg-blue-nuanced = "#12154a"
bg-magenta-nuanced = "#2f0c3f"
bg-cyan-nuanced = "#042837"

# Uncommon accent background and foreground pairs

bg-clay = "#49191a"
fg-clay = "#f1b090"

bg-ochre = "#462f20"
fg-ochre = "#e0d09c"

bg-lavender = "#38325c"
fg-lavender = "#dfc0f0"

bg-sage = "#143e32"
fg-sage = "#c3e7d4"
