# flake-freshness package monitoring configuration
#
# Group packages by their nixpkgs input sources.
# These inputs should match the specialized inputs defined in your flake.nix
#
# Copy this file to ~/.config/flake-freshness/freshness.toml and customize
# to track the packages you care about.

[packages]

# AI Tools (bleeding edge)
pkgs-ai = ["claude-code", "gemini-cli"]

# Development Tools (editors, LSPs, formatters)
pkgs-dev-tools = ["helix", "zed-editor", "vscode"]

# Flutter/Dart Development
pkgs-dev-flutter = ["flutter", "dart"]

# Rust Development
pkgs-dev-rust = ["rustc", "cargo", "rust-analyzer"]

# Android Development
pkgs-dev-android = [
  # "android-studio"
]

# Desktop Environments
pkgs-desktop = [
  # Core COSMIC components
  "cosmic-session",
  "cosmic-comp",
  "cosmic-greeter",
  "cosmic-panel",
  "cosmic-settings",
  "cosmic-files",
  "cosmic-edit",
  "cosmic-launcher",
]

# User Applications
pkgs-apps = ["signal-desktop-bin", "google-chrome"]
